### ISSUE TITLE
pypi outdated

### ISSUE THREAD

**Issue by castelao** [IQuOD/wodpy#10]
Hi,

I believe the package at pypi is outdated, so it does not contain WOD4Cotede.

https://travis-ci.org/castelao/AutoQC

Thanks,

**Comment by katieannemills** [comment]
Version 1.2 got pushed to pypi earlier this month; that tag was applied at 607e09ed261702459080c029a0e50707ca70c764, which is later than your CoTeDe commits - so it should be in there. What version of `wodpy` do you have after doing `pip install --upgrade wodpy`?

**Comment by castelao** [comment]
That's strange:

https://pypi.python.org/pypi?%3Aaction=search&term=wodpy&submit=search

don't show 1.2, but if you go into 1.1.0, it does acknowledge that the latest version is 1.2!

pip upgrade stops on 1.1, probably due the same reason the website search don't show it.

**Comment by katieannemills** [comment]
Hm - when I did `pip upgrade`, it took me to 1.2.

**Comment by castelao** [comment]
A fresh new virtualenv did installed 1.2, but pip search, pip upgrade and Travis don't see that.

**Comment by katieannemills** [comment]
Can you show me what you get when you do `pip upgrade`? In the iquod/autoqc docker container, I get:

```
root@13bcbdfce57c:/QC-current# pip install --upgrade wodpy
Collecting wodpy
  Downloading wodpy-1.2.0.tar.gz
...
```

**Comment by castelao** [comment]
Looks like there is something going on with pypi. There are more people complaining about similar things with other packages. Would you mind to try to setup.py register again? Maybe that creates a new record in the index.

The exact same procedure failed earlier today, but it did upgrade now. Although the search is still failing.

`root@757a641dce60:/# pip search wodpy`
`wodpy     - A parser for the WOD data format, described in`
`http://data.nodc.noaa.gov/woa/WOD/DOC/wodreadme.pdf`
`INSTALLED: 1.1.0 (latest)`

`root@757a641dce60:/# pip install --upgrade wodpy`
`Collecting wodpy`
`Downloading wodpy-1.2.0.tar.gz`
`...`

**Comment by katieannemills** [comment]
Will `setup register` do anything? I always thought that was a one-time thing, when creating a new package. What we could do, is try bumping the version number; if you send a fix for the discussion in #5, I will merge that and ship 1.2.1.

**Comment by castelao** [comment]
I believe I re-registered before to fix a typo on description, but release 1.2.1 is probably a better solution.

Sorry, what else is missing on #5 ?

**Comment by katieannemills** [comment]
> Sorry, what else is missing on #5 ?

Nothing! I just hadn't noticed your commits from earlier this week, thanks!

I just pushed 1.3.0 (not 1.2.1 since this was more than a bugfix) - let me know if that kicked things into shape. Otherwise I'd be inclined to wait and see if pypi acknowledges the problem and sorts it out themselves, since as you say, others are seeing this too.

**Comment by castelao** [comment]
Great! Thank you.

Should we close this?
