### ISSUE TITLE
What is time() returning?

### ISSUE THREAD

**Issue by rowanwins** [IQuOD/wodpy#11]
Gday,

I just wanted some clarification on what time() is returning. It looks like hours are just 0-23 but the minutes are a bit trickier to interpret.

I'm trying to work out if they are actual minute values or a %.
For example a t() reading of 2.8 is really 2:48 

Any advice would be great, Im not sure if this a thing with WOD data generally or a wodpy issue.

Cheers
Rowan

**Comment by katieannemills** [comment]
Hi @rowanwins - yes, your interpretation is correct; over on AutoQC we unpack wod-time with:

```
def parseTime(time):
    '''
    convert a WOD time on [0,24) to ints: hour [0,23], minute [0, 59], second [0, 59]
    '''
    hour = np.floor(time)
    minute = np.floor(time*60) % 60
    second = np.floor(time*3600) % 60

    return int(hour), int(minute), int(second)
```

**Comment by rowanwins** [comment]
Thanks for the clarification @BillMills
