### ISSUE TITLE
Reading of Originator station code from Character header

### ISSUE THREAD

**Issue by BecCowley** [IQuOD/wodpy#14]
@BillMills, I have a student trying to extract originator station codes from WOD ascii using the wodpy library. Having a bit of trouble understanding if we can do that. There are potentially three bits of information in the character header from the originator - Orignators cruise, originator's station code and Principal Investigator. We seem to be able to read the first, but not the second.

Can you assist? 
@oceanaustin is the student.

Thanks!

**Comment by katieannemills** [comment]
Hi @BecCowley - cruise is available, but station code and PI were never unpacked as we didn't need them for IQuOD; that said, we could add them in. I'm traveling the next few days, but I will try to find some time to implement this on the weekend.

**Comment by katieannemills** [comment]
Hi @BecCowley @oceanaustin,

I just pushed a first pass at this feature to [this branch here](https://github.com/BillMills/wodpy/tree/new-unpacks), but before I merge and release, a few questions / assumptions:

 - I assume a profile has either zero or one originator station.
 - The PIs are pulled as a list from the character header only.
 - Could you provide one wod-ascii profile with a known list of PIs (variable code and pi code), and a known station? For testing purposes, to spot check that we are in fact getting the right answer.

**Comment by BecCowley** [comment]
@BillMills, @oceanaustin, I think that the WOD format only allows for either the originator cruise ID OR the originator cast ID OR the PI. So maybe we are wasting time here and it already is decoding correctly?

Here is a snippet from the character header from one of our casts from 2015. Originator cruise id is in bold and it seems that field 4 indicates what type of data. 1 = cruiseid, 2 = cast id, 3 = PI. There is no option for all three in this format. I think the WOD is only keeping our cruise ID information.

1011 6**MJ3401**25817116601448421355011108181102229110223222072233110125411000222670

Full profile attached.
[MJsingle.txt](https://github.com/IQuOD/wodpy/files/645164/MJsingle.txt)

**Comment by katieannemills** [comment]
Hi folks - okay, that clears a few things up; I had originally failed to appreciate the difference between 'cruise' and 'originator cruise', but that's sorted out now - ideally we should be testing against one profile that has an originator cruise (like the one you posted), and another profile that has an originator station, but seeing as they unpack in the exact same way from the exact same place and are mutually exclusive, I think we can move ahead in the interests of unblocking @oceanaustin. If you have a profile with an originator station handy, post it here so I can fill out the rest of the tests suite.

This content will land in version 1.4.0, which I will stamp and release once I resolve #13 (tonight if we're lucky) - I'll post here once it ships. Let me know any other requests or concerns.

**Comment by katieannemills** [comment]
Alright, originator station, originator cruise and PI list should all be available in 1.4.0, which is now live on pypi; let me know if this works for you, and please feel free to post other feature requests!
