### ISSUE TITLE
WOD format edge case

### ISSUE THREAD

**Issue by katieannemills** [IQuOD/wodpy#18]
File: https://data.nodc.noaa.gov/woa/WOD/YEARLY/XBT/STD/XBTS2016.gz
Profile ID: 17453687

Wodpy is choking on this profile due to the `-` character concluding the substring `65000010-`. This `-` appears to be the sole character in the 'value' field for a level variable. @BoyerWOD, can you offer any insight here? A single `-` represents a missing value in the sigfigs field, but neither I nor wodpy knows what this is meant to mean in the value field.

For convenience, full profile text is:
```
C3875817453687995122272016 11533217355361123453-46212451 1110111533021421011 6OZ
20402932111166014093212330223135501045417880255018231811012291102232110623311012
54110527111012911102011000033281500110500332831002201000332838002201500332837002
20200033282000220250033281400220300033280300220350033280300220400033280300220450
03328040022050003328120022055003328120022060003328120022065003328120022070003328
12002207500332804002208000332804002208500332804002209000332803002209500332803003
30100003328060033012500332805003301500033276800330175003327570033020000332755003
30225003327510033025000332743003302750033267600330300003326370033032500332553003
30350003324800033037500332397003304000033234200330425003322660033045000332211003
304750033217100330500003321210033055000222570033060000222200033065000010-0033070
000232-220033075000232-210033080000232-280033085000232-330033090000232-3700

```

**Comment by katieannemills** [comment]
The same profile as a CSV:

```
#--------------------------------------------------------------------------------,
CAST                        ,,       17453687,WOD Unique Cast Number,WOD code,
NODC Cruise ID              ,,99-12227       ,,,
Originators Station ID      ,,   5501823.0000,,,real,
Originators Cruise ID       ,,OZ2040         ,,,
Latitude                    ,,         61.123,decimal degrees,,
Longitude                   ,,         -4.621,decimal degrees,,
Year                        ,,           2016,,,
Month                       ,,              1,,,
Day                         ,,             15,,,
Time                        ,,           1.73,decimal hours (UT),,
METADATA,
Country                     ,,             99,NODC code,UNKNOWN
Accession Number            ,,        140932.,NODC code,,
Project                     ,,           223.,NODC code,GLOBAL TEMPERATURE-SALINITY PROFILE PROGRAM (GTSPP),
Platform                    ,,         10454.,OCL code,NORRONA (Call sign OZ2040; built 04.2003; IMO9227390;Faeroe Islands),
probe_type                  ,,             2.,OCL_code,XBT,
Recorder type               ,,             6.,WMO code 4770,SIPPICAN MK21,
Standard depth equation used,,             1.,,corrected,
systematic_fix              ,,             5.,WOD code,Levitus et al.; 2009 applied (XBT/MBT),
Real time data              ,,             1.,,real-time data,
Database origin             ,,             2.,WOD code,GTSP Project,
Instrument       ,Temperature,           214.,WOD code,XBT: DEEP BLUE (SIPPICAN),
VARIABLES ,Depth     ,F,O,Temperatur ,F,O,,
UNITS     ,m         , , ,degrees C ,, , ,,
Prof-Flag ,          ,0, ,          ,0, ,,
         1,       0.0,0, ,      8.15,0, ,
         2,       5.0,0, ,      8.31,0, ,
         3,      10.0,0, ,      8.38,0, ,
         4,      15.0,0, ,      8.37,0, ,
         5,      20.0,0, ,      8.20,0, ,
         6,      25.0,0, ,      8.14,0, ,
         7,      30.0,0, ,      8.03,0, ,
         8,      35.0,0, ,      8.03,0, ,
         9,      40.0,0, ,      8.03,0, ,
        10,      45.0,0, ,      8.04,0, ,
        11,      50.0,0, ,      8.12,0, ,
        12,      55.0,0, ,      8.12,0, ,
        13,      60.0,0, ,      8.12,0, ,
        14,      65.0,0, ,      8.12,0, ,
        15,      70.0,0, ,      8.12,0, ,
        16,      75.0,0, ,      8.04,0, ,
        17,      80.0,0, ,      8.04,0, ,
        18,      85.0,0, ,      8.04,0, ,
        19,      90.0,0, ,      8.03,0, ,
        20,      95.0,0, ,      8.03,0, ,
        21,     100.0,0, ,      8.06,0, ,
        22,     125.0,0, ,      8.05,0, ,
        23,     150.0,0, ,      7.68,0, ,
        24,     175.0,0, ,      7.57,0, ,
        25,     200.0,0, ,      7.55,0, ,
        26,     225.0,0, ,      7.51,0, ,
        27,     250.0,0, ,      7.43,0, ,
        28,     275.0,0, ,      6.76,0, ,
        29,     300.0,0, ,      6.37,0, ,
        30,     325.0,0, ,      5.53,0, ,
        31,     350.0,0, ,      4.80,0, ,
        32,     375.0,0, ,      3.97,0, ,
        33,     400.0,0, ,      3.42,0, ,
        34,     425.0,0, ,      2.66,0, ,
        35,     450.0,0, ,      2.11,0, ,
        36,     475.0,0, ,      1.71,0, ,
        37,     500.0,0, ,      1.21,0, ,
        38,     550.0,0, ,      0.57,0, ,
        39,     600.0,0, ,      0.20,0, ,
        40,     650.0,0, ,       -0.,0, ,
        41,     700.0,0, ,     -0.22,0, ,
        42,     750.0,0, ,     -0.21,0, ,
        43,     800.0,0, ,     -0.28,0, ,
        44,     850.0,0, ,     -0.33,0, ,
        45,     900.0,0, ,     -0.37,0, ,
```

The 650m depth level reads as `-0.`, which would be consistent with how we're reading the above profile if the `-` character doesn't count as part of the number of digits (1). Seems like a reasonable interpretation, but I want to see a confirmation in the docs before I merge any change to the parser.

**Comment by BecCowley** [comment]
@BillMills. Looking at the data in netcdf format, I can see that this data is from the Norrona, which is a ferry run by Thomas Rossby and others for an XBT line. The data looks like it is missing a couple of bits of information - the country shouldn't be unknown, and the data point at 650m looks like a translation error. It is missing the other part of the temperature after the decimal point. Also, this data looks like it has come off the GTS (source is GTSPP), so the full resolution data is available elsewhere (probably in the WOD as a duplicate?). 
So, there are a couple of issues here, and these should be fed back to the data collectors and GTSPP and WOD.
But, to solve your actual problem of the data point - I'm not clear on how the reader needs to handle it. I expect you will come across faulty data like this regularly - so maybe throw an error for someone to investigate?

**Comment by katieannemills** [comment]
Thanks, @BecCowley! I agree, seems fishy - @s-good ran through almost 400k profiles with this parser and never came across this problem as far as I know, which is why I'm reluctant to change its current logic without more clarity.

Re: feeding back to the data collectors, GTSPP & WOD - you would know best how to do this appropriately, let me know how I should proceed. Looking ahead, would it be useful to automate efforts to detect problems of this nature? If we can articulate specifically what sort of thing should be raised in this manner, we can look into producing a more comprehensive survey, rather than flagging individual profiles ad hoc.

For wodpy, I'm taking suggestions on how to handle faults of this nature. I actually like that it errors out when given an invalid profile, since keeping on going in that case is a short path to systematics. But, it might be interesting to think about how to provide more useful insight into *why* the profile is corrupt. Will think on this, suggestions welcome.

**Comment by katieannemills** [comment]
@BoyerWOD identified this as a rare problem upstream in the WODselect infrastructure which:

 > will only occur when the original temperature value is exactly 0.00 with only one significant figure and the bias corrected temperature is negative, but greater than -0.05.

Closing as not a wodpy bug - thanks all for the investigation!
