### ISSUE TITLE
question about nitrite and nitrate in OSD.

### ISSUE THREAD

**Issue by Vipermdl** [IQuOD/wodpy#29]
Hi， this is a good job for WOD database. I have an question about the [paper](https://www.ncei.noaa.gov/data/oceans/woa/WOD/DOC/wodreadme.pdf) said the OSD data have nitrite and nitrate, but the project of wodpy did not suply the interface of that, so how I can have this information about nitrite and nitrate by wodpy? Thank you!
![QQ截图20210911205511](https://user-images.githubusercontent.com/32351961/132948523-d6332992-7578-4dda-8801-fb2b7230d30f.png)

**Comment by katieannemills** [comment]
Hi @Vipermdl - to look up any variable (assuming it is present in your profile):
 - Find the variable code from table 3 of https://www.ncei.noaa.gov/data/oceans/woa/WOD/DOC/wodreadme.pdf (Nitrate is code 8)
 - Look up the index of this variable in your profile `p` with `index = p.var_index(code)`
 - Finally, extract the data with `p.var_data(index)`

So for example, try the following on a `profile` object named `p`:

```
nitrate = p.var_data(p.var_index(8))
```

then `nitrate` should have what you're looking for. Please post here if it doesn't work for you.
