### ISSUE TITLE
Possibility of extracting data of all (x,y) coordinates in the dataset

### ISSUE THREAD

**Issue by AhmedAredah** [IQuOD/wodpy#41]
I am doing a research that depends on variables such as salinity, temperature, wave height, wave direction, and depth in world oceans. Is it possible to extract these values for all coordinate in the dataset?

I would appreciate your guidance in doing so? Thank you.

**Comment by katieannemills** [comment]
Hi @AhmedAredah, thanks for asking. When you say 'the dataset', what exactly do you mean? wodpy parses WOD-ASCII or WOD netCDF files you have previously downloaded; you can certainly loop over your files and use wodpy to read anything you like from all of them. For example, if you have a bunch of WOD-ASCII files in a directory `./data`:

```
import os
from wodpy import wod

def process_files_in_directory(directory):
        for filename in os.listdir(directory):
                filepath = os.path.join(directory, filename)
                print(filepath)
                fid = open(filepath)
                profile = wod.WodProfile(fid)
                while True:
                        print(profile.uid()) # or whatever you want to do
                        if not profile.is_last_profile_in_file(fid):
                                profile = wod.WodProfile(fid)
                        else:
                                break



directory_path = './data'
process_files_in_directory(directory_path)
```

I'm going to close out here as this is working as expected, but feel free to ask followup questions below.
